### ISSUE TITLE
repeating Lua Call Stacks by Kverneland PW 100 - 12 Plow

### ISSUE THREAD

**Issue by headhunter84** [900hasse/FS22_REAimplements#3]
**Using Kverneland PW 100 - 12 Plow on field triggers a repeating Lua Call Stack.** 

_2022-03-05 07:51 Warning (script): 'setTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2022-03-05 07:51   D:\auto_builder\cache\svn\0ebd205709dafcdbd3fef400d64b8406\src\base\scripting\lua\LuaScriptSystem.cpp (903): expectedType == Value::VoidType || expectedType == Value::ClassType
2022-03-05 07:51 LUA call stack:
  =C:/Users/xxxx/Documents/My Games/FarmingSimulator2022/mods/FS22_REAimplements/REAimplements.lua (1088) : setTranslation
  =C:/Users/xxxx/Documents/My Games/FarmingSimulator2022/mods/FS22_REAimplements/REAimplements.lua (501) : UpdateGroundTypeNodes
  =C:/Users/xxxx/Documents/My Games/FarmingSimulator2022/mods/FS22_REAimplements/REAimplements.lua (455) : UpdateForcePulltype
  =C:/Users/xxxx/Documents/My Games/FarmingSimulator2022/mods/FS22_REAimplements/REAimplements.lua (262) : UpdatePowerMultiplier
  dataS/scripts/BaseMission.lua (1263) : update
  dataS/scripts/FSBaseMission.lua (1974) : update
  dataS/scripts/missions/mission00.lua (583) : update
  dataS/scripts/main.lua (1381) : update_

**Comment by DrewCZ** [comment]
same for me:
`2022-03-24 22:41 Warning (script): 'setTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2022-03-24 22:41   D:\auto_builder\cache\svn\3e7613655f548b9eea177e6a8510a10e\src\base\scripting\lua\LuaScriptSystem.cpp (903): expectedType == Value::VoidType || expectedType == Value::ClassType
2022-03-24 22:41 LUA call stack:
  =D:/DataTata/FarmMods22/FS22_REAimplements/REAimplements.lua (1088) : setTranslation
  =D:/DataTata/FarmMods22/FS22_REAimplements/REAimplements.lua (501) : UpdateGroundTypeNodes
  =D:/DataTata/FarmMods22/FS22_REAimplements/REAimplements.lua (455) : UpdateForcePulltype
  =D:/DataTata/FarmMods22/FS22_REAimplements/REAimplements.lua (262) : UpdatePowerMultiplier
  dataS/scripts/BaseMission.lua (1263) : update
  dataS/scripts/FSBaseMission.lua (1974) : update
  dataS/scripts/missions/mission00.lua (583) : update
  dataS/scripts/main.lua (1381) : update
`

**Comment by DrewCZ** [comment]
glad to see you back @900hasse
